# Generated by Django 5.0.4 on 2024-04-27 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_club', models.ManyToManyField(blank=True, null=True, to='myappname.bookclub')),
                ('profile_pic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myappname.profilephoto')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('sku', models.IntegerField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myappname.bookimage')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myappname.publisher')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myappname.user')),
            ],
        ),
    ]
